### ISSUE TITLE
Why can't start with official mariadb (not bitnami/mariadb)

### ISSUE THREAD

**Issue by duanhdan** [bitnami/bitnami-docker-laravel#101]
**Description**
I tried to deploy laravel app in my macbook and connect app to an mariadb container (image from official docker hub) but I always got this message:

```
Trying to connect to mariadb at 172.18.0.2. Attempt 26.
Error: Couldn't connect to mariadb.
```
I've searched for some issue and see that on [entrypoint](https://github.com/bitnami/bitnami-docker-laravel/blob/master/5/ol-7/rootfs/app-entrypoint.sh#L20), container has to connect to mariadb via curl. Everything is ok if I use `bitnami/mariadb:10.1` image. Please someone help me to use this docker image with official mariadb docker image.

**Steps to reproduce the issue**

- Deploy mariadb container from `mariadb` image

- Deploy laravel app via `bitnami/laravel:5-debian-9` image -> Can't start service

- Redeploy with `bitnami/mariadb:10.1` image -> Everything is ok

**Describe the results you expected**
I want to use laravel app with mariadb container from `mariadb` image.

**Version**

- Output of `uname -a`

```
Darwin xxx-xxx-xxx.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

- Output of `docker version`

```
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker Desktop
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: docker-desktop
ID: JT2H:NAGR:QPU4:VLRY:NIIV:PR5W:MPPY:EF4V:UZWQ:LA34:LGPH:JLWF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 79
 Goroutines: 95
 System Time: 2019-05-04T05:34:36.1043281Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `echo $BITNAMI_IMAGE_VERSION`
```
5.8.3-debian-9-r50
```

**Comment by duanhdan** [comment]
I have to use `entrypoint: ''` in docker-compose to stop default entrypoint script. Still need helping from community

**Comment by alemorcuq** [comment]
Hi, @duanhdan.

I'm not able to reproduce your issue. Can you give me some detailed steps in order to reproduce? I've tried deploying with `docker-compose` and it worked. This is the file I'm using:

```docker-compose
version: '2'

services:
  mariadb:
    image: 'mariadb:10.1'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=my_password

  myapp:
    tty: true
    image: bitnami/laravel:5-debian-9
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
```

Regards,
Alejandro

**Comment by duanhdan** [comment]
Hi @alemorcuq,
Thank you for taking your time. I've created docker-compose file for local dev:

```
version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - development

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Volumes/Development/docker/volumes/portainer:/data
    environment:
      VIRTUAL_HOST: portainer.test
      VIRTUAL_PORT: 9000
    depends_on:
      - proxy
    networks:
      - development

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
      - ./configurations/mariadb.cnf:/etc/mysql/mariadb.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Ho_Chi_Minh'
    networks:
      - development

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      VIRTUAL_HOST: phpmyadmin.test
      VIRTUAL_PORT: 80
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ''
    depends_on:
      - mariadb
    networks:
      - development

  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    networks: 
      - development

networks:
  development:
    external: true
```

And each project I used one file:

```
version: "3"

services:
  ebay-portal:
    tty: true
    image: bitnami/laravel
    restart: always
    volumes:
      - /Volumes/Development/projects/ebay-portal:/app
    environment:
      VIRTUAL_HOST: ebay-portal.test
      VIRTUAL_PORT: 80
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: dev_ebay
      DB_USERNAME: dev
      DB_PASSWORD: Dev@2019
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: 'Asia/Ho_Chi_Minh'
    networks:
      - development

networks:
  development:
    external: true
```

But I got this logs from laravel app container:

```
Welcome to the Bitnami laravel container
,Error: Couldn't connect to mariadb.
,Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
,
,Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues
,Installing/Updating Laravel dependencies (composer)
,Loading composer repositories with package information
,Installing dependencies (including require-dev) from lock file
,Nothing to install or update
,Generating optimized autoload files
,> Illuminate\Foundation\ComposerScripts::postAutoloadDump
,Discovered Package: beyondcode/laravel-dump-server
,> @php artisan package:discover --ansi
,Discovered Package: fideloper/proxy
,Discovered Package: laravel/tinker
,Discovered Package: nesbot/carbon
,Discovered Package: nunomaduro/collision
,Package manifest generated successfully.
,Dependencies installed
,
,Welcome to the Bitnami laravel container
,Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
,Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues
,
,Installing/Updating Laravel dependencies (composer)
,Loading composer repositories with package information
,Installing dependencies (including require-dev) from lock file
,Nothing to install or update
,Generating optimized autoload files
,> Illuminate\Foundation\ComposerScripts::postAutoloadDump
,> @php artisan package:discover --ansi
,Discovered Package: beyondcode/laravel-dump-server
,Discovered Package: fideloper/proxy
,Discovered Package: laravel/tinker
,Discovered Package: nesbot/carbon
,Discovered Package: nunomaduro/collision
,Package manifest generated successfully.
,Dependencies installed
,Connecting to mariadb at 172.18.0.7
,Trying to connect to mariadb at 172.18.0.7. Attempt 1.
,Trying to connect to mariadb at 172.18.0.7. Attempt 2.
,Trying to connect to mariadb at 172.18.0.7. Attempt 3.
,Trying to connect to mariadb at 172.18.0.7. Attempt 5.
,Trying to connect to mariadb at 172.18.0.7. Attempt 4.
,Trying to connect to mariadb at 172.18.0.7. Attempt 6.
,Trying to connect to mariadb at 172.18.0.7. Attempt 7.
,Trying to connect to mariadb at 172.18.0.7. Attempt 9.
,Trying to connect to mariadb at 172.18.0.7. Attempt 8.
,Trying to connect to mariadb at 172.18.0.7. Attempt 10.
,Trying to connect to mariadb at 172.18.0.7. Attempt 11.
,Trying to connect to mariadb at 172.18.0.7. Attempt 12.
,Trying to connect to mariadb at 172.18.0.7. Attempt 13.
,Trying to connect to mariadb at 172.18.0.7. Attempt 14.
,Trying to connect to mariadb at 172.18.0.7. Attempt 16.
,Trying to connect to mariadb at 172.18.0.7. Attempt 15.
,Trying to connect to mariadb at 172.18.0.7. Attempt 17.
,Trying to connect to mariadb at 172.18.0.7. Attempt 18.
,Trying to connect to mariadb at 172.18.0.7. Attempt 22.
,Trying to connect to mariadb at 172.18.0.7. Attempt 21.
,Trying to connect to mariadb at 172.18.0.7. Attempt 19.
,Trying to connect to mariadb at 172.18.0.7. Attempt 20.
,Trying to connect to mariadb at 172.18.0.7. Attempt 23.
,Trying to connect to mariadb at 172.18.0.7. Attempt 24.
,Trying to connect to mariadb at 172.18.0.7. Attempt 25.
,Trying to connect to mariadb at 172.18.0.7. Attempt 26.
,Trying to connect to mariadb at 172.18.0.7. Attempt 28.
,Trying to connect to mariadb at 172.18.0.7. Attempt 27.
,Trying to connect to mariadb at 172.18.0.7. Attempt 29.
,Error: Couldn't connect to mariadb.
```

But if I ssh into the container, I can use `php artisan tinker` to test the mariadb connection.
