### ISSUE TITLE
Container stuck while connecting to db

### ISSUE THREAD

**Issue by yanko-ivanov** [bitnami/bitnami-docker-laravel#120]
Hello! I seem to have a problem with a simple laravel application + mariadb container. 
Apparently, according to the app-entrypoint.sh script I've no connectivity to the mariadb container, so it shuts down the container after 30 tries. Which is absolutely wrong, because if I attach to the laravel container during that sequence, I can run the artisan migrations etc - I can see the mariadb container and I can connect to it.

It seems that the problem boils down to this line:

https://github.com/bitnami/bitnami-docker-laravel/blob/0e4809f2cb2e77127321615fcf5314d044a017fd/6/debian-9/rootfs/app-entrypoint.sh#L26

This is my docker-compose.yml:
```
version: '3'

services:
mariadb:
    image: 'bitnami/mariadb:latest'
    env_file:
      - .env
    expose:
      - "3306"
    ports:
      - 3306:3306
    links:
      - app

  app:
    tty: true
    image: bitnami/laravel:6-debian-9
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./docker/app-entrypoint.sh:/app-entrypoint.sh
```

And these are the relevant settings in my .env:

```
DB_CONNECTION=mysql
DB_HOST=mariadb
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

### Docker-compose settings for mariadb
MARIADB_ROOT_USER=root
MARIADB_ROOT_PASSWORD=pass123
MARIADB_USER=homestead
MARIADB_DATABASE=homestead
MARIADB_PASSWORD=secret
```

I've temporarily fixed the issue with overriding the app-entrypoint script with my own, and the only difference with the provided one being that instead of the call to the *wait_for_db* function, I'm doing a  *sleep 15*, which has the drawback of waiting for 15s but doesn't *exit 1* on the whole app.
Also, I'm really not certain what one would expect to happen when curl-ing mariadb silently. This is beyond me, but I'd wager it's not an optimal solution. :)

**Comment by jotamartos** [comment]
Hi @yanko-ivanov,

Just a quick note to let you know that the team is checking this issue and we will update it as soon as we have more information.

Thanks

**Comment by jotamartos** [comment]
Hi @yanko-ivanov,

We tried to reproduce the error but we couldn't do so. The docker-compose.yml file we used was this one 

```
version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    env_file:
      - .env
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - MARIADB_USER=my_user
#      - MARIADB_DATABASE=my_database
#      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    image: bitnami/laravel:6-debian-9
    env_file:
      - .env
#    environment:
#      - DB_HOST=mariadb
#      - DB_USERNAME=my_user
#      - DB_DATABASE=my_database
#      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
```

and the .env file is the same one you shared

```
DB_CONNECTION=mysql
DB_HOST=mariadb
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

### Docker-compose settings for mariadb
MARIADB_ROOT_USER=root
MARIADB_ROOT_PASSWORD=pass123
MARIADB_USER=homestead
MARIADB_DATABASE=homestead
MARIADB_PASSWORD=secret
```

We found this information in the logs 

```
mariadb_1  | mariadb 14:12:49.11 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 14:12:49.38 INFO  ==> Stopping mariadb
myapp_1    | Trying to connect to mariadb at 172.21.0.2. Attempt 3.
mariadb_1  | mariadb 14:12:52.39 INFO  ==> ** MariaDB setup finished! **
mariadb_1  |
mariadb_1  | mariadb 14:12:52.42 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.43-MariaDB) starting as process 1 ...
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_1  |
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB: Waiting for purge to start
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.45-86.1 started; log sequence number 1616727
mariadb_1  | 2019-12-16 14:12:52 140082103187200 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Warning] 'proxies_priv' entry '@% root@52e36cb032fe' ignored in --skip-name-resolve mode.
mariadb_1  | 2019-12-16 14:12:52 140082849941376 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.1.43-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
myapp_1    | Configuring the database
myapp_1    | Migration table created successfully.
myapp_1    | Migrating: 2014_10_12_000000_create_users_table
myapp_1    | Migrated:  2014_10_12_000000_create_users_table (0.03 seconds)
myapp_1    | Migrating: 2014_10_12_100000_create_password_resets_table
myapp_1    | Migrated:  2014_10_12_100000_create_password_resets_table (0.03 seconds)
myapp_1    | Migrating: 2019_08_19_000000_create_failed_jobs_table
myapp_1    | Migrated:  2019_08_19_000000_create_failed_jobs_table (0.02 seconds)
myapp_1    | Initialization finished
myapp_1    | Laravel development server started: http://0.0.0.0:3000
```

As you can see, the laravel container failed to connect to MariaDB 3 times but then the database finished the configuration step and the Laravel container could connect to it. Can you try to run the containers again with the files I shared? Please ensure MariaDB shows the same information when you try to access it.

In case that doesn't work, could you please share with us the following information?
- The specs of the host machine
- Your host operating system
- Your docker and docker-compose version

Thanks
