### ISSUE TITLE
Change to Mysql

### ISSUE THREAD

**Issue by JFernandoGomez** [bitnami/bitnami-docker-laravel#122]
how can I change from mariadb to Mysql with this image?

**Comment by alemorcuq** [comment]
Hi, @JFernandoGomez.

This `docker-compose.yml` works for me:

```yaml
❯ cat docker-compose.yml
version: '2'

services:
  mysql:
    image: 'bitnami/mysql:5.7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=my_password

  myapp:
    tty: true
    image: bitnami/laravel:6-debian-9
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
```
