### ISSUE TITLE
Use https for the bitnami-docker-laravel container

### ISSUE THREAD

**Issue by HendrikJan** [bitnami/bitnami-docker-laravel#124]
**Description**

This is more a question that an issue.  
(I'm sorry if this is not the right place for that. The Bitnami community forum sent me here)  

The question is: How can I enable https (ssl) on the bitnami-docker-laravel container?
I couldn't find any information in the documentation.

**Steps to reproduce the issue:**

My current setup is this:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      # connect your dbeaver/workbench to localhost:${WORKBENCH_PORT}
      - ${DOCKER_DB_PORT}:${DB_PORT}
    # volumes:
      # Do not load databases here, as there is no
      # good way for other containers to wait for this to finish
      # - ./database:/docker-entrypoint-initdb.d
  myapp:
    tty: true
    image: bitnami/laravel:6-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
    ports:
      - ${DOCKER_WEB_PORT}:3000
    volumes:
      - ./:/app
```
**Describe the results you received:**

My current setup gives me the webpage using http.

**Describe the results you expected:**

I would like the webpage to be served over https

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.3.0-40-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.27GiB
Name: Laptop
ID: MRHB:4NBQ:O6KQ:MNCQ:7M4Y:GUJ2:2DHP:7AM7:G7PJ:ZVCR:QSTW:6JGZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```
