### ISSUE TITLE
Error: Directory public does not exist

### ISSUE THREAD

**Issue by vilarinholeo** [bitnami/bitnami-docker-laravel#132]
Hello, I'm trying to run the container by adding the mongodb extension and using a lumen code. But whenever I try to run compose up I get the error:

```
Welcome to the Bitnami laravel container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues

Directory public does not exist.
```

Does anyone know what can it be?

Here is my Dockerfile:
```
FROM docker.io/bitnami/laravel:7-debian-10
USER root

WORKDIR /app

RUN sudo install_packages git autoconf build-essential pkg-config libmemcached-dev libmemcached11 libmemcachedutil2 libhashkit2
RUN sudo pecl install mongodb
RUN sudo echo extention=mongodb.so >> /opt/bitnami/php/etc/php.ini

EXPOSE 5000
CMD [ "php", "-S=0.0.0.0:5000", "-t=public" ]

```

My docker-compose.yml:
```
version: "3.7"
services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  app:
    build: "."
    container_name: dashboard-pwa-back
    volumes:
      - ./:/app
    ports:
      - 5000:5000
```
