### ISSUE TITLE
error when installing in docker

### ISSUE THREAD

**Issue by ekonomicron** [bitnami/bitnami-docker-laravel#153]
- host os: windows 11
- docker version: docker desktop 4.3.0
- output of docker info:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 12
  Running: 0
  Paused: 0
  Stopped: 12
 Images: 25
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 2.823GiB
 Name: docker-desktop
 ID: NRFQ:CPXM:Q3WU:IFVD:Y6HO:QB2G:OTGL:MIKF:FFPZ:OUP2:TD66:KRKM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- version of this container: `bitnami/laravel:latest`
- command used to run the container:

```yaml
version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    ports:
      - 3307:3306

  myapp:
    tty: true
    image: bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    privileged: true # Privileged mode could be required to run this container under Windows
```

below is the docker-compose logs

```console
myapp_1    | Installing/Updating Laravel dependencies (composer)
myapp_1    | Loading composer repositories with package information
myapp_1    | Updating dependencies
myapp_1    | Nothing to modify in lock file
myapp_1    | Installing dependencies from lock file (including require-dev)
myapp_1    | Nothing to install, update or remove
myapp_1    | Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
myapp_1    | Generating optimized autoload files
myapp_1    | > Illuminate\Foundation\ComposerScripts::postAutoloadDump
myapp_1    | Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception
myapp_1    |
myapp_1    |
myapp_1    |   [ErrorException]
myapp_1    |   require(/app/vendor/composer/../laravel/framework/src/Illuminate/Support/helpers.php): failed to open stream: No such file or directory
myapp_1    |
```
