### ISSUE TITLE
How to run `composer install` before `php artisan serve`?

### ISSUE THREAD

**Issue by lamualfa** [bitnami/bitnami-docker-laravel#159]
![image](https://user-images.githubusercontent.com/39755201/152649208-d9c23351-840c-47df-8271-02bff90699d0.png)

Error when running the laravel project using bitnami laravel image. maybe the error occurs because I haven't run `composer install` before. I didn't run it because I didn't want to install PHP outside the docker container.

The question is, is there a way to run `composer install` before the `php artisan serve`?

I am using docker-compose to handle the docker container.

```yml
version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lamualfa-root-password
      - MYSQL_USER=lamualfa-user
      - MYSQL_PASSWORD=lamualfa-password
      - MYSQL_DATABASE=lamualfa-database
    ports:
      - '3001:3306'
  backend:
    image: docker.io/bitnami/laravel:8
    ports:
      - '8000:8000'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=lamualfa-user
      - DB_PASSWORD=lamualfa-password
      - DB_DATABASE=lamualfa-database
    volumes:
      - './backend:/app:z'
    depends_on:
      - db

```
